services:
  camel-java8:
    build:
      dockerfile: Dockerfile.java8
    image: camel-build:java8
    container_name: camel-build-java8
    stdin_open: true
    tty: true
    volumes:
      - ./git-repo:/git
      - ./m2-repo:/root/.m2/repository
